/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingAssistantRouteImport } from './routes/meeting-assistant'
import { Route as ResearchAssistantRouteImport } from './routes/research-assistant'
import { Route as SavedRouteImport } from './routes/saved'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingAssistantRoute = MeetingAssistantRouteImport.update({
  id: '/meeting-assistant',
  path: '/meeting-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchAssistantRoute = ResearchAssistantRouteImport.update({
  id: '/research-assistant',
  path: '/research-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meeting-assistant': typeof MeetingAssistantRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/saved': typeof SavedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meeting-assistant': typeof MeetingAssistantRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/saved': typeof SavedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meeting-assistant': typeof MeetingAssistantRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/saved': typeof SavedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meeting-assistant' | '/research-assistant' | '/saved'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meeting-assistant' | '/research-assistant' | '/saved'
  id: '__root__' | '/' | '/meeting-assistant' | '/research-assistant' | '/saved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetingAssistantRoute: typeof MeetingAssistantRoute
  ResearchAssistantRoute: typeof ResearchAssistantRoute
  SavedRoute: typeof SavedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-assistant': {
      id: '/meeting-assistant'
      path: '/meeting-assistant'
      fullPath: '/meeting-assistant'
      preLoaderRoute: typeof MeetingAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-assistant': {
      id: '/research-assistant'
      path: '/research-assistant'
      fullPath: '/research-assistant'
      preLoaderRoute: typeof ResearchAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetingAssistantRoute: MeetingAssistantRoute,
  ResearchAssistantRoute: ResearchAssistantRoute,
  SavedRoute: SavedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
