/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedMeetingAssistantRouteImport } from './routes/_authenticated/meeting-assistant'
import { Route as AuthenticatedResearchAssistantRouteImport } from './routes/_authenticated/research-assistant'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/_authenticated/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeetingAssistantRoute =
  AuthenticatedMeetingAssistantRouteImport.update({
    id: '/_authenticated/meeting-assistant',
    path: '/meeting-assistant',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedResearchAssistantRoute =
  AuthenticatedResearchAssistantRouteImport.update({
    id: '/_authenticated/research-assistant',
    path: '/research-assistant',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/_authenticated/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/chat': typeof AuthenticatedChatRoute
  '/meeting-assistant': typeof AuthenticatedMeetingAssistantRoute
  '/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/chat': typeof AuthenticatedChatRoute
  '/meeting-assistant': typeof AuthenticatedMeetingAssistantRoute
  '/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/meeting-assistant': typeof AuthenticatedMeetingAssistantRoute
  '/_authenticated/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chat'
    | '/meeting-assistant'
    | '/research-assistant'
    | '/saved'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/meeting-assistant'
    | '/research-assistant'
    | '/saved'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/chat'
    | '/_authenticated/meeting-assistant'
    | '/_authenticated/research-assistant'
    | '/_authenticated/saved'
    | '/_authenticated/settings'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedMeetingAssistantRoute: typeof AuthenticatedMeetingAssistantRoute
  AuthenticatedResearchAssistantRoute: typeof AuthenticatedResearchAssistantRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meeting-assistant': {
      id: '/_authenticated/meeting-assistant'
      path: '/meeting-assistant'
      fullPath: '/meeting-assistant'
      preLoaderRoute: typeof AuthenticatedMeetingAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/research-assistant': {
      id: '/_authenticated/research-assistant'
      path: '/research-assistant'
      fullPath: '/research-assistant'
      preLoaderRoute: typeof AuthenticatedResearchAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedMeetingAssistantRoute: AuthenticatedMeetingAssistantRoute,
  AuthenticatedResearchAssistantRoute: AuthenticatedResearchAssistantRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
